version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - betree
  ignore:
  - dependency-name: react-router
    versions:
    - ">= 5.a"
    - "< 6"
  - dependency-name: redux-form
    versions:
    - "> 6.8.0"
