env:
  browser: true
  es6: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: "off"
  max-len:
    - error
    - code: 90
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
