env:
  browser: true
  es6: true
  jest: true
  node: true
extends: 'airbnb'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jsx-a11y
  - import
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - never
  max-len:
    - error
    - code: 85
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  react/no-multi-comp: ['warn']
  react/sort-comp: ['warn']
  no-restricted-globals: ["error", "event", "fdescribe"]
  jsx-a11y/anchor-is-valid: 
    - error
    - components: ['Link']
      specialLink: ['To']
  jsx-a11y/alt-text: ['warn']

  # Following rule haves been disabled for compatibility with
  # existing code. Some of them should be re-activated in the future.

  no-console: off
  no-shadow: off
  object-curly-spacing: off
  object-curly-newline: off
  comma-dangle: off
  function-paren-newline: off
  arrow-parens: off
  arrow-body-style: off
  curly: off
  no-use-before-define: off
  no-param-reassign: off
  camelcase: off
  no-underscore-dangle: off
  no-restricted-syntax: off
  prefer-destructuring: off
  consistent-return: off
  class-methods-use-this: off
  prefer-promise-reject-errors: off
  react/jsx-tag-spacing: off
  react/prop-types: off
  import/prefer-default-export: off
  import/export: off
  block-spacing: off
  brace-style: off
