# Netlify configuration  |
# -----------------------/

# For staging and pre-deploys
[context.deploy-preview.environment]
  ALGOLIA_APP_ID = "N5GW2EAIFX"
  ALGOLIA_USAGE_API_KEY = "bde675591087b21d0dbc992981c26c5f"
  FB_APP_ID = "1923415864574767"
  GRAPHQL_API_URL = "https://graphql.staging.captainfact.io"
  HTTP_API_URL = "https://api.staging.captainfact.io"
  WS_API_URL = "wss://api.staging.captainfact.io/socket"
  JS_ENV = "staging"
  FRONTEND_URL = "https://staging.captainfact.io"

[context.branch-deploy.environment]
  ALGOLIA_APP_ID = "N5GW2EAIFX"
  ALGOLIA_USAGE_API_KEY = "bde675591087b21d0dbc992981c26c5f"
  FB_APP_ID = "1923415864574767"
  GRAPHQL_API_URL = "https://graphql.staging.captainfact.io"
  HTTP_API_URL = "https://api.staging.captainfact.io"
  WS_API_URL = "wss://api.staging.captainfact.io/socket"
  JS_ENV = "staging"
  FRONTEND_URL = "https://staging.captainfact.io"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "
      default-src 'self';
      object-src 'self' https://captainfact.io;
      script-src 'self' 'unsafe-inline' https://www.youtube.com https://s.ytimg.com https://stats.captainfact.io https://cdnjs.cloudflare.com 'sha256-Y0GQ8oBo2E9DpNIINLboEYGSH1dyzdm4iSyTkt/qmBU=' 'sha256-kQJBbA6+P0lReef1s4voWq9FqF74NDZdtVkCAnL7Xoo=';
      style-src 'self' 'unsafe-inline' data:;
      connect-src 'self' HTTP_API_BASE_URL WS_API_BASE_URL GRAPHQL_API_BASE_URL https://query.wikidata.org https://www.wikidata.org https://api.rollbar.com https://*.algolianet.com;
      img-src 'self' STATIC_RESOURCES_URL https://stats.captainfact.io https://api.adorable.io https://gravatar.com https://img.youtube.com data:;
      frame-src https://www.youtube.com https://stats.captainfact.io https://opencollective.com/;
      base-uri 'self';
    "
