# Netlify configuration. We use Netlify for pull requests previews. |
# ------------------------------------------------------------------/

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
