#!/usr/bin/env bash
# You need to have woff2 installed! See https://github.com/google/woff2

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 ICOMOON_BUNDLE.ZIP"
  exit 1
fi

cd -- "$(dirname $0)/.."
WORKDIR=/tmp/captain-fact-icomoon
FONTS_DIR=app/styles/_fonts
ICONS_LIST=app/styles/_global/icons_list.scss
FONT_NAME=icomoon
CONFIG_FILE=config/icomoon_icons.json

rm -rf ${WORKDIR}
mkdir ${WORKDIR}


unzip "$1" -d ${WORKDIR}

echo "🌙 Copy fonts to $FONT_NAME"
cp ${WORKDIR}/fonts/* ${FONTS_DIR}

echo "🌙 Creating woff2 from ttf file in $FONTS_DIR/$FONT_NAME.woff2"
woff2_compress ${FONTS_DIR}/${FONT_NAME}.ttf

echo "🌙 Generating CSS file: $ICONS_LIST"
echo -e "/* [!] DO NOT EDIT THIS FILE. Automatically generated from $0 */\n" > ${ICONS_LIST}
cat ${WORKDIR}/style.css | tail -n +27 >> ${ICONS_LIST}

echo "🌙 Saving config to $CONFIG_FILE"
cp ${WORKDIR}/selection.json ${CONFIG_FILE}
