export default [
  {
    id: 1,
    image_url: 'https://picsum.photos/500/300/?random',
    title: 'Est-ce une bonne chose de rendre les transports en gratuits ?',
    quote: 'Une grande réforme fiscale à été adoptée aux États-Unis l\'année dernière',
    author_avatar_url: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    author_name: 'Pierre Sabatier',
    quote_time: '7:52',
    featuring: ['Olivier Delamarche', 'Alain Juillet'],
    starred: true,
    comments_number: 12,
    verified: true
  },
  {
    id: 2,
    image_url: 'https://picsum.photos/500/300/?random',
    title: 'Est-ce une bonne chose de rendre les transports en gratuits ?',
    quote: 'Une grande réforme fiscale à été adoptée aux États-Unis l\'année dernière',
    author_avatar_url: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    author_name: 'Pierre Sabatier',
    quote_time: '7:52',
    featuring: ['Olivier Delamarche', 'Alain Juillet'],
    starred: false,
    comments_number: 13,
    verified: false
  },
  {
    id: 3,
    image_url: 'https://picsum.photos/500/300/?random',
    title: 'Est-ce une bonne chose de rendre les transports en gratuits ?',
    quote: 'Une grande réforme fiscale à été adoptée aux États-Unis l\'année dernière',
    author_avatar_url: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    author_name: 'Pierre Sabatier',
    quote_time: '7:52',
    featuring: ['Olivier Delamarche', 'Alain Juillet'],
    starred: false,
    comments_number: 13,
    verified: false
  },
  {
    id: 4,
    image_url: 'https://picsum.photos/500/300/?random',
    title: 'Est-ce une bonne chose de rendre les transports en gratuits ?',
    quote: 'Une grande réforme fiscale à été adoptée aux États-Unis l\'année dernière',
    author_avatar_url: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    author_name: 'Pierre Sabatier',
    quote_time: '7:52',
    featuring: ['Olivier Delamarche', 'Alain Juillet'],
    starred: false,
    comments_number: 13,
    verified: false
  },
  {
    id: 5,
    image_url: 'https://picsum.photos/500/300/?random',
    title: 'Est-ce une bonne chose de rendre les transports en gratuits ?',
    quote: 'Une grande réforme fiscale à été adoptée aux États-Unis l\'année dernière',
    author_avatar_url: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    author_name: 'Pierre Sabatier',
    quote_time: '7:52',
    featuring: ['Olivier Delamarche', 'Alain Juillet'],
    starred: false,
    comments_number: 13,
    verified: false
  },
  {
    id: 6,
    image_url: 'https://picsum.photos/500/300/?random',
    title: 'Est-ce une bonne chose de rendre les transports en gratuits ?',
    quote: 'Une grande réforme fiscale à été adoptée aux États-Unis l\'année dernière',
    author_avatar_url: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    author_name: 'Pierre Sabatier',
    quote_time: '7:52',
    featuring: ['Olivier Delamarche', 'Alain Juillet'],
    starred: false,
    comments_number: 13,
    verified: false
  },
  {
    id: 7,
    image_url: 'https://picsum.photos/500/300/?random',
    title: 'Est-ce une bonne chose de rendre les transports en gratuits ?',
    quote: 'Une grande réforme fiscale à été adoptée aux États-Unis l\'année dernière',
    author_avatar_url: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    author_name: 'Pierre Sabatier',
    quote_time: '7:52',
    featuring: ['Olivier Delamarche', 'Alain Juillet'],
    starred: false,
    comments_number: 13,
    verified: false
  },
  {
    id: 8,
    image_url: 'https://picsum.photos/500/300/?random',
    title: 'Est-ce une bonne chose de rendre les transports en gratuits ?',
    quote: 'Une grande réforme fiscale à été adoptée aux États-Unis l\'année dernière',
    author_avatar_url: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    author_name: 'Pierre Sabatier',
    quote_time: '7:52',
    featuring: ['Olivier Delamarche', 'Alain Juillet'],
    starred: false,
    comments_number: 13,
    verified: false
  },
  {
    id: 10,
    image_url: 'https://picsum.photos/500/300/?random',
    title: 'Est-ce une bonne chose de rendre les transports en gratuits ?',
    quote: 'Une grande réforme fiscale à été adoptée aux États-Unis l\'année dernière',
    author_avatar_url: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    author_name: 'Pierre Sabatier',
    quote_time: '7:52',
    featuring: ['Olivier Delamarche', 'Alain Juillet'],
    starred: false,
    comments_number: 13,
    verified: false
  }
]
