#!/usr/bin/env bash
# You need to have woff2 installed! See https://github.com/google/woff2

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 ICOMOON_BUNDLE.ZIP"
  exit 1
fi

cd -- "$(dirname $0)/.."
WORKDIR=/tmp/captain-fact-icomoon

rm -rf ${WORKDIR}
mkdir ${WORKDIR}


unzip "$1" -d ${WORKDIR}

cp ${WORKDIR}/fonts/* app/assets/assets/fonts
woff2_compress app/assets/assets/fonts/icomoon.ttf
echo -e "/* [!] DO NOT EDIT THIS FILE. Automatically generated from $0 */\n" > app/styles/_global/icons_list.scss
cat ${WORKDIR}/style.css | tail -n +27 >> app/styles/_global/icons_list.scss
cp ${WORKDIR}/selection.json config/icomoon_icons.json
