name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: 'npm'
      - name: Install dependencies
        run: CYPRESS_INSTALL_BINARY=0 npm ci
      - run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: 'npm'
      - name: Install dependencies
        run: CYPRESS_INSTALL_BINARY=0 npm ci
      - run: npm run prettier:check

  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: 'npm'
      - name: Install dependencies
        run: CYPRESS_INSTALL_BINARY=0 npm ci
      - run: npm run typescript

  unused-exports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: 'npm'
      - name: Install dependencies
        run: CYPRESS_INSTALL_BINARY=0 npm ci
      - run: npm run ts-unused-exports

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: 'npm'
      - name: Install dependencies
        run: CYPRESS_INSTALL_BINARY=0 npm ci
      - name: Run tests
        run: npm run coverage
      - name: Post tests coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
